[package]
authors = ["Mark Sinclair <mark.edward.x@gmail.com>"]
name = "torus"
version = "0.1.0"

[dependencies]
clap = "^2"
cmdline-parser = "0.1.0"
linefeed = "~0.2.3"
prettytable-rs = "^0.6"
rusqlite = "0.11.0"
xdg = "^2.1"
